app/osf/__init__.py
from flask import Blueprint

osf = Blueprint("osf",__name__)

from . import views

app/osf/views.py
from flask import flash, redirect, render_template, url_for,request,session,Markup, abort
from flask_login import login_required, login_user, logout_user,current_user
from flask_paginate import Pagination, get_page_args

from . import osf
from .. import db
from sqlalchemy import extract
from ..api import *
from ..models import *
from ..func_ import *
from ..sms import sms_
from bson import json_util
import simplejson as json
import geocoder
import config as conf
# import pdfkit as pdf
import os

# @osf.route('/be/',methods=['GET', 'POST'])
# def enroll():
# 	is_admin = False
# 	if "is_admin" in session:
# 		is_admin = session["is_admin"]
# 	config = pdf.configuration(wkhtmltopdf='/usr/bin/wkhtmltopdf')
# 	pdf.from_string(render_template("osf/bienrollement.html"), 'enrollment.pdf',configuration=config)
# 	return render_template("osf/bienrollement.html",is_admin=is_admin)


@osf.route('/',methods=['GET', 'POST'])
def land():
	is_admin = False
	if "is_admin" in session:
		is_admin = session["is_admin"]

	bus_types = CompanyType.query.all()
	return render_template("osf/index.html",title="Home",bus_types=bus_types,is_admin=is_admin)


@osf.route('/vline/status/<int:business>/<int:status>/', methods=['GET', 'POST'])
@login_required
def vlinestatus(business,status):
	company_ = Company.query.filter_by(id=business).first()
	if status == 1:
		flash("Appointment was flagged as Honoured.")
	else:
		if status == 2:
			flash("Appointment was flagged as Not Honoured.")

	return redirect(url_for('osf.companies',company_type=company_.company_type_id))


@osf.route('/vline/<int:business>/', methods=['GET', 'POST'])
@login_required
def vline(business):
	is_admin = False
	if "is_admin" in session:
		is_admin = session["is_admin"]

	customer_ = Customer.query.filter_by(email=current_user.email).first()
	joined = ""
	if customer_:
		rejoin = False
		place_in_line = 0
		company_ = Company.query.filter_by(id=business).first()
		vline_ = Vline.query.filter_by(company_id=business,created_date=today()).first()

		if vline_:
			vlineup_ = Vlineup.query.filter_by(company_id=business,user_id=current_user.id,line_id=vline_.id).first()
			if vlineup_:
				rejoin = True
				joined = vlineup_.joined
			
			if vline_.serving != -1:
				place_in_line = len(vline_.lineup)

				if vlineup_:
					rejoin = True
					joined = vlineup_.joined
					place_in_line = vlineup_.place_in_line

			else:
				flash("This virtual line is closed.")
				return redirect(url_for('osf.companies',company_type=company_.company_type_id))
		else:
			flash(f"{company_.name} has no active virtual lines for today.")
			return redirect(url_for('osf.companies',company_type=company_.company_type_id))
	else:
		flash("You need a customer account to access that resource.")
		return redirect(url_for('osf.account'))
	

	return render_template("osf/vline.html",title="Virtual Line",company=company_,rejoin=rejoin,place_in_line=place_in_line,line=vline_,joined=joined,is_admin=is_admin)

@osf.route('/vline/join/<int:business>/', methods=['GET', 'POST'])
@login_required
def joinvline(business):

	customer_ = Customer.query.filter_by(email=current_user.email).first()
	if customer_:
		rejoin = True
		place_in_line = 0
		company_ = Company.query.filter_by(id=business).first()
		vline_ = Vline.query.filter_by(company_id=business,created_date=today()).first()
		if vline_:
			if vline_.serving != -1:
				inline_ = Vlineup.query.filter_by(line_id=vline_.id,company_id=business,user_id=current_user.id).first()
				if not inline_:
					place_in_line = len(vline_.lineup) + 1
					vlineup_ = Vlineup(line_id=vline_.id,company_id=business,user_id=current_user.id,joined=now(),place_in_line=place_in_line)
					error = db_commit_add_or_revert(vlineup_)
					if not error:
						flash("Your place in line has been secured.","success")
						rejoin = False
					else:
						flash("There was an error placing you in line. You may try again or contact admin if the problem persists.","error")
				else:
					rejoin = True
					place_in_line = inline_.place_in_line
					flash("You are already in this line","success")

			else:
				flash("This Virtual line is closed")
				return redirect(url_for('osf.companies',company_type=company_.company_type_id))
		else:
			flash(f'{company_.name} has no active virtual lines.')
	else:
		flash("You need a customer account to access that resource.")
		return redirect(url_for('osf.account'))
	return redirect(url_for('osf.vline',business=business))
	

@osf.route('/about/', methods=['GET', 'POST'])
def about():

	is_admin = False
	if "is_admin" in session:
		is_admin = session["is_admin"]
	return render_template("osf/about.html",title="About",is_admin=is_admin)

@osf.route('/contact/', methods=['GET', 'POST'])
def contact():

	is_admin = False
	if "is_admin" in session:
		is_admin = session["is_admin"]
	return render_template("osf/contact.html",title="Contact",is_admin=is_admin)

@osf.route('/companies/<int:company_type>/', methods=['GET', 'POST'])
def companies(company_type):
	comp_type = "All"
	is_admin = False
	comps_ = None
	if "is_admin" in session:
		is_admin = session["is_admin"]

	fav_companies = []

	if company_type:
		comps_ = CompanyType.query.filter_by(id=company_type).first()

	business_of_type = Company.query.filter_by(company_type_id=company_type,published=1).all()
	if current_user.is_authenticated:
		customer_ = Customer.query.filter_by(email=current_user.email).first()
		companies_ = FavouriteCompany.query.filter_by(customer_id=customer_.id).all()

		for company in companies_:
			fav_companies.append(company.company_id)
	if len(business_of_type) < 1:
		return redirect(url_for('osf.land'))

	if comps_:
		comp_type = comps_.name

	return render_template("osf/companies.html",title=f"Companies::{comp_type}",resgistered_businesses=business_of_type,is_admin=is_admin,fav_companies=fav_companies)

@osf.route('/account/',defaults={"account_type":None}, methods=['GET', 'POST'])
@osf.route('/account/<account_type>/', methods=['GET', 'POST'])
def account(account_type):
	is_admin = False
	comp_types = getCompanyType()
	form = request.form
	activation_link = None
	activation_busi_link = None
	lock_login = None

	if "account_type" in form: 
		if int(form["account_type"]) == 3:
			user = User.query.filter_by(email=form["bus_email"]).first()
			if not user:
				new_user = {"username_":make_user_name(form["bus_owner"]),"fullname_":form["bus_owner"],"email_":form["bus_email"],"password_":form["bus_pass"]}
				res = createUser(new_user,request.files["image_"]) 
				if "success" in res:
					user_ = res["user"]
					owner_id = user_.id
			else:
				owner_id = user.id
				user_ = user

			company = Company.query.filter_by(email=form["bus_email"]).first()

			if not company:
				location = f'{form["bus_address"]},{form["bus_state"]},{form["bus_city"]},{form["bus_postal"]}'
				company = {"name":form["bus_name"],"created_date":today(),"contact":form["bus_phone"],"email":form["bus_email"],"tax":form["bus_tax"],"owner_id":owner_id,"type_id":form["bus_type"],"location":location,"status":0,"update":0}#account to be verified b4 it becomes active

				res = createCompany(company,request.files["image_"],request.files["store_front_image"])
				if "success" in res:
					company_ = res["company"]
					# add business as customer by default
					customer_ = Customer(name=form["bus_owner"],email=form["bus_email"],created_date=now(),last_business=None,street=form["bus_address"],street2={form["bus_state"]},city=form["bus_city"],zip_code=form["bus_postal"],active=1,customer_type="normal",contact=form["bus_phone"],barcode="",credit_limit=None,tax_id="000000000",avatar="img/customers/default.png",company_name=form["bus_name"])   
					error = db_commit_add_or_revert(customer_)
					token = company_.get_activation_token()
					params = {"type":"company","name":company_.owner.fullname,"app_link":url_for('osf.land',_external=True),"rec_link":url_for('osf.activate',token=token,_external=True),"email":company_.email,"contact":Markup(f'Email: {conf.COMPANY_EMAIL}<br>Mobile: {conf.COMPANY_MOBILE}<br>Telephone: {conf.COMPANY_TELEPHONE}<br><span style="font-size:12px;">You can also reach out to us using the contact us form on the portal.</span><br>')}
					user_.add_notification("activation", "company", user_.id, "Company Account Activation", json.dumps(params, default=json_util.default), 0)

				msg, msg_type = flash_res_msg(res)
				if msg:
					flash(msg,msg_type)
			else:
				company_ = company

			if not company_.active:
				if date_dif(user_.created_date,convertDateTime(now())) >= 5:
					flash(f"An Account associated with {user_.email} already exist, however it is not active. Resend the activation link with the button below.")
					activation_busi_link = Markup(f"<a class='btn btn-success' id='activation_link' href='{url_for('osf.resend',account_type=2,email=company_.email)}'>Resend Activation link {date_dif(user_.created_date,convertDateTime(now()))}</a>")
			else:
				flash("Your Business Account is already active. You may need to use account recovery to regain access.")
		else:
			if int(form["account_type"]) == 2:
				user = User.query.filter_by(email=form["cus_email"]).first()
				cus_full_name = f'{form["cus_fname"]} {form["cus_lname"]}'

				if not user:
					new_user = {"username_":make_user_name(cus_full_name),"fullname_":cus_full_name,"email_":form["cus_email"],"password_":form["cus_pass"]}
					res = createUser(new_user,request.files["image_"]) 

					if "success" in res:
						user_ = res["user"]
						user_id = user_.id
				else:
					user_id = user.id
					user_ = user

				if user_id:
					customer = Customer.query.filter_by(email=form["cus_email"]).first()
					if not customer:

app/templates/osf/cart.html
{% import "bootstrap/utils.html" as utils %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Our Store Front Online {{ title }}</title>

    {% include "osf/osf_header.html" %}


</head>

<body>
    <!-- Search Wrapper Area Start -->
        {% include "osf/osf_search.html" %}
  
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        {% include "osf/osf_navigator.html" %}
       
        <!-- Header Area End -->
        

        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="cart-title mt-50">
                             {{ utils.flashed_messages() }}

                            <h2>Order #{{ order.id }} @ <a href="{{ url_for('osf.company',name=order.company.name,_id=order.company_id)}}">{{ order.company.name }} </a>
                                <a class="btn btn-info" href="{{ url_for('osf.shop',company=order.company_id)}}">Back To Shop</a>
                            </h2>
                        </div>
                        <div class="cart-table clearfix">
                            {% if order %}
                                <table class="table table-responsive">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th>Name</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for line in order.orderlines %}
                                            <tr>
                                                <td class="cart_product_img">
                                                    {% if line.name == 'base' %}
                                                        <a href="#"><img class="cart-img" src="{{ url_for('static',filename=line.product.image) }}" alt="{{ line.product.name }}"></a>
                                                    {% else %}
                                                        {% for variant in line.product.variants %}
                                                            {% if line.name == variant.name %}
                                                                <a href="#"><img class="cart-img" src="{{ url_for('static',filename=variant.image) }}" alt="{{ variant.name }}"></a>
                                                            {% endif %}
                                                        {% endfor %}
                                                    {% endif %}
                                                </td>
                                                <td class="cart_product_desc">
                                                    <h5>{{ line.product.name|capitalize }}</h5>
                                                    <span>{{ line.name|capitalize }}</span>
                                                </td>
                                                <td class="price">
                                                    <span>{{ toMoney(line.price) }}</span>
                                                </td>
                                                <td class="qty">
                                                    <div class="qty-btn d-flex">
                                                        <p>Qty</p>
                                                        <div class="quantity">
                                                            <span class="qty-minus"><i class="fa fa-minus" aria-hidden="true"></i></span>
                                                            <input type="number" item="{{ line.product_id }}" price="{{ line.price }}" v_name="{{ line.name }}" order="{{ line.order_id }}"  company="{{ order.company_id }}" class="qty-text" id="qty" step="1" min="1" max="20" name="quantity" value="{{ line.qty|int }}">
                                                            <span class="qty-plus"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                                        </div>
                                                        &nbsp;
                                                        &nbsp;
                                                        &nbsp;
                                                        <a href="{{ url_for('osf.remove_orderline',company=order.company_id,order=order.id,line=line.id,customer=order.customer_id)}}">
                                                            <i class="fa fa-trash"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                {% else %}
                                <div>
                                    <p>You have not selected any products from this company today.</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Order Total</h5>
                            <ul class="summary-table">
                                <li><span>Subtotal:</span> <span>{{ toMoney(order.sub_total) }}</span></li>
                                <li><span>Tax:</span> <span>{{ toMoney(order.tax_amount) }}</span></li>
                                <li><span>Total:</span> <span>{{ toMoney(order.total) }}</span></li>
                            </ul>
                            <div class="cart-btn mt-100">


                                {% if order.status|int == 0 %}
                                    {% if order.filter_state|upper == "NOT SENT" %}
                                        {% if order.company.closed %}
                                            <span class="btn btn-warning" title="{{ order.company.name }} is not processing any orders at this time. They are closed."> Company Closed</span>
                                        {% else %}
                                            <a href="{{ url_for('osf.sendorder',order=order.id,customer=order.customer_id,company=order.company_id)}}" class="btn amado-btn w-100" title="Send order for fulfilment.">Confirm Order</a>
                                        {% endif %}
                                    {% else %}
                                        <p><center>This order is in [ <sub>fulfilment pending</sub> ] status</center></p>
                                        <p>
                                            <center>
                                                Contact <span class="company"><a href="mailto:{{ order.company.email }}">{{ order.company.name }}</a></span> to get fulfilment progress 
                                            </center>
                                        </p>
                                    {% endif %}
                                {% else %}
                                        <p><center>This order has been flagged as being <span title="fulfilled: If you havent already picked up your order, you need to do so.">fulfilled.</center></p>
                                        <h6><center><sub>If you did not confirm this order please reach out to <u><a href="mailto:{{ order.company.email }}">{{ order.company.name }}</a></u> for clarification</sub></center></h6>
                                   
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->


{% include "osf/osf_footer.html" %}

 {% include "osf/osf_scripts.html" %}

</body>

</html>

app/templates/osf/osf_header.html
    <!-- Favicon  -->
    <!-- <link rel="icon" href="img/core-img/favicon.ico"> -->

      <!-- Favicon  -->
    <!-- <link rel="icon" href="img/core-img/favicon.ico"> -->
    {% include 'osf/osf_meta.html' %}
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ url_for('static',filename='img/ms-icon-144x144.png') }}">
<meta name="theme-color" content="#ffffff">

<link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static',filename='img/android-icon-192x192.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static',filename='img/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static',filename='img/favicon-96x96.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static',filename='img/favicon-16x16.png') }}">
<link rel="manifest" href="{{ url_for('static',filename='manifest.json') }}" crossorigin="use-credentials">

<!-- Core Style CSS -->
<link rel="stylesheet" href="{{ url_for('static',filename='styles/core-style.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='styles/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='styles/croppie.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='styles/invoice.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='styles/_profile.css') }}">
<link rel="stylesheet" href="{{ url_for('static',filename='styles/product_listings.css') }}">

<script type="text/javascript" src="{{ url_for('static',filename='js/jquery/jquery-2.2.4.min.js') }}"></script>
<script type="text/javascript" language="javascript" src="{{ url_for('static',filename='js/tablefilter.js') }}" > </script>

<script type="text/javascript" src="{{ url_for('static',filename='js/osf_glbs.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/osf.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='js/croppie.js') }}"></script>

app/templates/osf/osf_navigator.html
        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="{{ url_for('osf.land') }}"><img src="{{ url_for('static', filename='img/core-img/logo.png') }}" alt="Our-Store-Front-Online"></a>
                <span class="v-line"></span>
                
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="{{ url_for('osf.land') }}"><img src="{{ url_for('static', filename='img/core-img/logo.png') }}" alt="Our-Store-Front-Online"></a>
                <span class="v-line"></span>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><span class="log_in_as">{{ current_user.fullname }}</span></li>
                    {% if is_admin == 1 %}
                        <li><a href="{{ url_for('home.dashboard') }}" rel=“nofollow”>Administrator</a></li>
                    {% endif %}
                    <li class="active"><a href="{{ url_for('osf.land') }}">Home</a></li>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('osf.logout') }}">Log Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('osf.account') }}">Sign In</a></li>
                    {% endif %}
                    <li><a href="{{ url_for('osf.about') }}">About</a></li>
                   
                </ul>
            </nav>
            <!-- Button Group -->
    <!--         <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div> -->
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                
                <a href="{{ url_for('osf.orders') }}" class="cart-nav" rel=“nofollow”><img src="{{ url_for('static', filename='img/core-img/cart.png') }}" alt="Orders"> Orders</a>
                
                <a href="{{ url_for('osf.favourites') }}" class="fav-nav" rel=“nofollow”><img src="{{ url_for('static', filename='img/core-img/favorites.png') }}" alt="Favourites"> Favourites (
                    {% if current_user.is_authenticated %}
                        <span class="fav-count">{{ favourites(current_user.email) }}</span>
                    {% else %}
                        0
                    {% endif %}
                )
                </a>
                <a href="#" class="search-nav"><img src="{{ url_for('static', filename='img/core-img/search.png') }}" alt="Search"> Search</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <!-- <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a> -->
                <a href="https://www.instagram.com/ourstore_front_online/" target="_blank" data-toggle="tooltip" title="follow us on instagram"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="https://www.facebook.com/Our-Store-Front-Online-106677051142856/" target="_blank" data-toggle="tooltip" title="Like and follow our facebook page"><i class="fa fa-thumbs-up" aria-hidden="true"></i></a>
                <a href="#" onclick="javascript:social_sharer('whatsapp_share_osfo');" data-toggle="tooltip" title="Share with your whatsapp contacts"><i class="fa fa-whatsapp" aria-hidden="true"></i></a>
                <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.ourstorefront.online" target="_blank" data-toggle="tooltip" title="Share OSFO on facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>

            </div>
        </header>

app/templates/osf/vline.html
{% import "bootstrap/utils.html" as utils %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Our Store Front Online | {{ title }}</title>

    {% include "osf/osf_header.html" %}
</head>

<body>
    <!-- Search Wrapper Area Start -->
        {% include "osf/osf_search.html" %}
  
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        {% include "osf/osf_navigator.html" %}
      
        <!-- Header Area End -->

        <!-- Product Catagories Area Start -->
        <div class="products-catagories-area clearfix">
  {{ utils.flashed_messages() }}

          <!--   <div class="amado-pro-catagory clearfix">
                <h6>You are the {{ ordinal(company.vline|length + 1) }} person here</h6>
                <h5>Do you want to <a class="btn bth-info" href="{{ url_for('osf.joinvline',business=company.id)}}">Join the Line</a></h5>
            </div>
 -->
    <div id="booking" class="section">
        <br>
       
        <div class="section-center">
            <div  title="This Company offers you the ability to start a transaction here online and complete it when you get there. Click the ! to start the process."> <a href="{{ url_for('pos.pos_',company=company.id) }}"><i class="fa fa-exclamation-circle fa-4x"></i></a>
        </div>
            <h3><center>Hello {{ current_user.fullname }}, </center></h3>
                <h4><center>Welcome to the Virtual Line for {{ company.name }}</center></h4>

            <div class="container">

                <div class="row">
                    <div class="booking-form">
                        <form>
                            <div class="row no-margin">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <span class="form-label">Place in Line</span>
                                        <input class="form-control" type="text" placeholder="" value="{{ ordinal(place_in_line) }}" disabled>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="row no-margin">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <span class="form-label">Serving Number </span>
                                                <input class="form-control" type="Number" value="{{ line.serving }}" disabled>
                                            </div>
                                        </div>
                                       <!--  <div class="col-md-5">
                                            <div class="form-group">
                                                <span class="form-label">Check out</span>
                                                <input class="form-control" type="date" required>
                                            </div>
                                        </div> -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <span class="form-label">Persons Waiting</span>
                                                <input class="form-control" type="text" value="{{ line.lineup|length }}" disabled="">
                                                  
                                                <span class="select-arrow"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-btn">
                                        {% if rejoin %}
                                            <span class="rejoin">You joined line @ {{ toTime(joined) }}</span>
                                            <div>
                                                <h6><center>Was your Appointment:</center></h6>
                                                <button class="btn btn-success"><a href="{{ url_for('osf.vlinestatus',business=company.id,status=1)}}">Honoured <i class="fa fa-thumbs-up"></i></a></button>&nbsp;&nbsp;Or&nbsp;&nbsp; 
                                                <button class="btn btn-warning"><a href="{{ url_for('osf.vlinestatus',business=company.id,status=2)}}">Not Honoured  <i class="fa fa-thumbs-down"></i></a></button>
                                            </div>
                                            <!-- <span></span> -->
                                        {% else %}
                                            <button class="submit-btn"><a href="{{ url_for('osf.joinvline',business=company.id)}}">Join Line</a></button>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
        </div>
              
        
        <!-- Product Catagories Area End -->
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    <!-- ##### Newsletter Area Start ##### -->
 
    <!-- ##### Newsletter Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
{% include "osf/osf_footer.html" %}
    <!-- ##### Footer Area End ##### -->

 {% include "osf/osf_scripts.html" %}


</body>

</html>