app/mods/__init__.py
from flask import Blueprint

mods = Blueprint("mods",__name__)

from . import views

app/mods/views.py
from flask import flash, redirect, render_template, url_for,request,session,abort
from flask_login import login_required, login_user, logout_user,current_user
from openpyxl import load_workbook
from . import mods
from .. import db
from ..api import *
from ..models import *
from ..func_ import *
from ..sms import sms_
import urllib.request
import simplejson as json
import config as conf

title_ = "OSFO"
empty_form = []

@mods.route('/orders') 
@login_required
def orders():
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	company_ = Company.query.filter_by(id=company.id).first()
	return render_template("mods/company/orders.html",title=title_+" | Orders",year=year(),company=company_)

@mods.route('/order/flag/fulfilled/<int:order>/') 
@login_required
def fillOrder(order):
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	order_ = Order.query.filter_by(id=order,company_id=company.id).first()
	if order_:
		# mail_send_res = sendOrderConfirmation(order,"fulfilled")
		confirmation_msg = f"Your order has been fulfilled. Order#{order_.id} has been confirmed [fulfilled] by #{order_.company.name}. You can now pickup your items and complete transaction @ store location."
		params = {"type":"fulfilled","order":order_.id,"message":confirmation_msg,"name":order_.customer.name,"app_link":url_for('osf.land',_external=True),"rec_link":url_for('osf.company',name=order_.company.name,_id=order_.company.id,_external=True),"email":order_.customer.email,"contact":Markup(f'Email: {conf.COMPANY_EMAIL}<br>Mobile: {conf.COMPANY_MOBILE}<br>Telephone: {conf.COMPANY_TELEPHONE}<br><span style="font-size:12px;">You can also reach out to us using the contact us form on the portal.</span><br>')}
		company.owner.add_notification("confirmation", "company", company.owner.id, "Order Fulfilled Confirmation", json.dumps(params, default=json_util.default), 0)
		if order_.customer.contact:
			sms_(f'1{order_.contact.contact}', confirmation_msg)
		order_.status = 1
		error = db_commit_update_or_revert()
		flash("fulfilment notification will be sent to customer.")

	return redirect(url_for('mods.orders'))

@mods.route('/order/flag/paid/<int:order>/') 
@login_required
def paidOrder(order):
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	order_ = Order.query.filter_by(id=order,company_id=company.id).first()
	if order_:
		order_.paid = 1
		order_.amount_due = 0
		error = db_commit_update_or_revert()
		if not error:
			# TODO send notification to customer of order fulfilment with pickup / delivery options
			flash("fulfilment alert has been sent to customer.")

		return redirect(url_for('mods.orders'))

@mods.route('/customers/')
@login_required
def customers():
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	customers = getCustomersByCompany(company.id)
	return render_template("mods/customer/customers.html",title=title_+" | Customers",year=year(),customers=customers,company=company)

@mods.route('/customer/add/')
@login_required
def customerAdder():
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	customers = getCustomersByCompany(company.id)
	return render_template("mods/customer/customer_adder.html",title=title_+" | Customers",form='add',year=year(),customers=customers,customer=[1],company=company)

@mods.route('/customers/create', methods=['GET','POST'])
@login_required
def addCustomer():
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	form = request.form
	ajax = True if "ajax" in form else False
		
	if ajax:
		res = createCustomer(form,"")
		customers = getCustomersByCompany(session["company"])
		
		ret = {}
		ret["result"] = {}
		ret["result"]["form"] = [res["form"]] if res["form"] else empty_form
		ret["result"]["types"] = [customers]
		ret["result"]["error"] = res["error"] 

		return json.dumps(ret,default=lambda a: {'id':a.id,'name':a.name } )
	else:
		res = createCustomer(form,request.files["image_"])	
		customers = getCustomersByCompany(session["company"])
		form_action = 'add'
	
		msg, msg_type = flash_res_msg(res)
		if msg:
			flash(msg,msg_type)


		if "action" in res and res["action"] == 'update':
			form_action = 'edit'

		return render_template("mods/customer/customer_adder.html",title=title_+" | Customers",form=form_action,year=year(),customers=customers,customer=res["form"],company=company)


@mods.route('/customers/edit/<int:customer_id>/', methods=['GET','POST'])
@login_required
def editCustomer(customer_id):
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	customers = getCustomersByCompany(company_id)
	customer = [1]
	if customer_id:
		customer = [getCustomerbyID(customer_id)]
	
	return render_template("mods/customer/customer_adder.html",title=title_+" | Customers",form='edit',year=year(),customers=customers,customer=customer,company=company)


@mods.route('/customers/remove/',methods=['GET','POST'])
@login_required
def removeCustomer():
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	form = request.form
	res = deleteCustomer(form)
	customers = getCustomersByCompany(company.id)

	msg, msg_type = flash_res_msg(res)
	if msg:
		flash(msg,msg_type)

	return render_template("mods/customer/customers.html",title=title_+" | Customers",year=year(),customers=customers,customer=res["form"],company=company)
	

@mods.route("/company/open/<int:company>/",methods=["POST","GET"])
@login_required
def openCompany(company):
	company_ = Company.query.filter_by(id=company).first()
	company_.closed = 0
	error = db_commit_update_or_revert()
	error = createPOSSession(company)
	if "success" in error:
		flash("Pos session is now active.","success")

	if not error:
		flash("Open Sign Erected successfully.","success")

	return redirect(url_for('home.dashboard'))

@mods.route("/company/publish/<int:company>/",methods=["POST","GET"])
@login_required
def publishCompany(company):
	company_ = Company.query.filter_by(id=company).first()
	product_ = Product.query.filter_by(company_id=company,status=1).first()
	if company_:
		if len(company_.products) > 0:
			if product_:	
				company_.published = 1
				error = db_commit_update_or_revert()
				if not error:
					flash("Your Company is now available to customers for browsing and sending in orders. Be prepared to fulfil those orders.","success")
					return redirect(url_for('mods.openCompany',company=company_.id))
						
				else:
					flash(f"{error}")
			else:
				flash("You have no active products to complete the publish action.")
		else:
			flash("Your company setup is incomplete. Ensure that you have products for customers to shop and your company location is set.","warning")
	else:
		abort(404)
	return redirect(url_for('home.dashboard'))

@mods.route("/company/retract/<int:company>/",methods=["POST","GET"])
@login_required
def retractCompany(company):
	company_ = Company.query.filter_by(id=company).first()
	company_.published = 0
	company_.closed = 1
	error = db_commit_update_or_revert()
	if not error:
		flash("Your Company has been retracted. Customers will no longer see your products.")
	else:
		flash(f"{error}")

	return redirect(url_for('home.dashboard'))


@mods.route("/company/pause/<int:company>/",methods=["POST","GET"])
@login_required
def pauseCompany(company):
	company_ = Company.query.filter_by(id=company).first()
	company_.paused = 1
	error = db_commit_update_or_revert()
	if not error:
		flash("Your Company has been paused, which means comsumers can only browse your product listings.")

	return redirect(url_for('home.dashboard'))


@mods.route("/company/close/<int:company>/",methods=["POST","GET"])
@login_required
def closeCompany(company):
	company_ = Company.query.filter_by(id=company).first()
	vline_ = Vline.query.filter_by(company_id=company,created_date=today()).first()

	if vline_ and vline_.active:
		flash("Close virtual line before attempting to close business.")
	else:
		company_.closed = 1
		error = db_commit_update_or_revert()
		if not error:
			flash("Close Sign Erected successfully.")
		else:
			flash(error)
	return redirect(url_for('home.dashboard'))


@mods.route("/company/create/",methods=["POST","GET"])
@login_required
def addCompany():
	# company = Company.query.filter_by(id=session["company"]["id"]).first()
	company = Company.query.filter_by(id=session["company"]["id"]).first()
	title_ = company.name
	form = request.form
	ajax = True if "ajax" in form else False
	
	if current_user:
		ctypes = getCompanyType()
		if "bus_name" in form:
			ohl_ = 1
			if form["bus_ohl"]:
				ohl_ = form["bus_ohl"]
				
			location = f'{form["bus_address"]},{form["bus_state"]},{form["bus_city"]},{form["bus_postal"]}'
			company_form = {"name":form["bus_name"],"twitter":form["bus_twitter"],"google":form["bus_google"],"coords":form["bus_coords"],"facebook":form["bus_facebook"],"contact":form["bus_phone"],"email":form["bus_email"],"tax":form["bus_tax"],"type_id":form["bus_type"],"order_hold_limit":ohl_,"location":location,"status":0,"update":1}
			#account to be verified b4 it becomes active
			res = createCompany(company_form,request.files["image_"],request.files["store_front_image"])
			msg, msg_type = flash_res_msg(res)
			if msg:
				flash(msg,msg_type)

			if "success" in res:
				company = res["company"]
				session["company"] = company.as_dict()

		else:
			location_arr = company.location.split(",")
			bus_address = location_arr[0]
			bus_state = None
			bus_city = None
			bus_postal = None
			if len(location_arr) > 1:
				bus_state = location_arr[1] 
			if len(location_arr) > 2:

app/templates/mods/customer/customer_adder.html

{% extends "home/index.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
	
		
		<div class="main-card mb-3 card">
            <div class="card-body">
              <h5 class="card-title">CUSTOMER REGISTRATION</h5>

				<form action="{{ url_for('mods.addCustomer') }}" method="post" role="form" id="customers_creator" enctype="multipart/form-data">
				    <input type="hidden" name="update" id="customers_update" value=0 />

		            <input type="hidden" name="created_date" value="" id="customer_date">
		            <input type="hidden" name="status" value="1" id="customer_status">
		            <input type="hidden" name="last_business" value="0000-00-00 00:00:00" id="customer_last_business">
					
					<div class="form-row">
						<div class="col-md-6">
                      		<div class="position-relative form-group">
								<label for="company_" class="col-form-label">Company</label>
								<select class="form-control" name="company_id" id="company_">
								    <option value="{{ company.id }}">{{ company.name }}</option>
								          
								   	{% if current_user.is_admin %}
										<option class="add_" value="add_company"> -- Add Company -- </option>
									{% endif %}
								</select>

							</div>
						</div>

						{% if form == 'add' %}
	                  		<div class="col-md-6">
	                      		<div class="position-relative form-group">

									<label for="customer_type" class="col-form-label">Customer Type</label>
									<select class="form-control" name="type" id="customer_type">
										<option value=""> --- Select --- </option>
										<option value="Employee">Employee</option>
										<option value="Company">Company</option>
										<option value="Partner">Partner</option>
										<option value="Normal">Normal</option>					
									</select>
								</div>
							</div>
						{% else %}
							<div class="col-md-6">
	                      		<div class="position-relative form-group">
									<input type="hidden" name="type" value="{{ customer[0].customer_type }}" class="form-control">
									<label for="customer_type" class="col-form-label">Customer Type</label>&nbsp;&nbsp;&nbsp;
									
									<span id="change_customer_type"><i class="fa fa-pen"></i></span>
									
									<input type="text" name="type" value="{{ customer[0].customer_type }}" class="form-control" disabled>
									
									<select class="form-control" name="type" id="customer_type_select_hide" disabled>
										<option value=""> --- Select --- </option>
										<option value="Employee">Employee</option>
										<option value="Company">Company</option>
										<option value="Partner">Partner</option>
										<option value="Normal">Normal</option>					
									</select>
								</div>
							</div>

						{% endif %}
				
					</div>


					{% for fv in customer %}
			
					<div class="form-row">
						<div class="col-md-4">
                      		<div class="position-relative form-group">
								<label for="customer_company" class="col-form-label">Customer Company</label>
						        <input class="form-control" type="text" name="company_name" placeholder="Enter Customer's Company Name" value="{{ fv.company.name if form == 'edit' else fv.company }}" id="customer_company" />	
					
							</div>
						</div>
						<div class="col-md-4">
                      		<div class="position-relative form-group">
								<label for="" class="col-form-label">Customer Name</label>
								<input class="form-control" type="text" name="name" placeholder="Enter Customer Name" value="{{ fv.name }}" id="customer_name">
							</div>
						</div>
			    
				    	<div class="col-md-4">
	                      	<div class="position-relative form-group">
								<label for="" class="col-form-label">Customer Email</label>
								<input class="form-control" type="email" name="email" placeholder="Enter Customer email" value="{{ fv.email }}" id="customer_email">
							</div>
						</div>
					</div>

					<div class="form-row">
						<div class="col-md-4">
							<div class="position-relative form-group">
								<label for="customer_street" class="col-form-label">Street </label>
								<input class="form-control" type="text" name="street" placeholder="Enter Customer Street" value="{{ fv.street }}" id="customer_street">
								</div>
						</div>
						<div class="col-md-4">
							<div class="position-relative form-group">

								<label for="customer_street2" class="col-form-label">Street 2</label>
								<input class="form-control" type="text" name="street2" placeholder="Enter Customer Street2" value="{{ fv.street2 }}" id="customer_street2">
							</div>
						</div>

						<div class="col-md-4">
	                  		<div class="position-relative form-group">
								<label for="customer_city" class="col-form-label">City</label>
								<input class="form-control" type="text" name="city" placeholder="Enter Customer City" value="{{ fv.city }}" id="customer_city">
							</div>
						</div>
					</div>

					<div class="form-row">
						<div class="col-md-4">
                      		<div class="position-relative form-group">
								<label for="customer_zip" class="col-form-label">Zip Code</label>
								<input class="form-control" type="text" name="zip" placeholder="Enter Customer Zip Code" value="{{ fv.zip }}" id="customer_zip">
							</div>
						</div>

						<div class="col-md-4">
                      		<div class="position-relative form-group">
								<label for="customer_contact" class="col-form-label">Contact</label>
								<input class="form-control" type="tel" name="contact" placeholder="Enter Customer Contact" value="{{ fv.contact }}" id="customer_contact">
							</div>
						</div>
						
						<!-- <div class="col-md-4">
                      		<div class="position-relative form-group">
								<label for="customer_barcode" class="col-form-label">Barcode</label>
							</div>
						</div> -->
								<input class="form-control" type="hidden" name="barcode" placeholder="Enter Customer Barcode" value="" id="customer_barcode">

						<div class="col-md-4">
	                      	<div class="position-relative form-group">
								<label for="customer_tax_id" class="col-form-label">Tax ID</label>
								<input class="form-control" type="text" name="tax_id" placeholder="Enter Customer Tax ID" value="{{ fv.tax_id }}" id="customer_tax">
							</div>
						</div>
					</div>

					<div class="form-row">
						

						<div class="col-md-6">
                      		<div class="position-relative form-group">
								<label for="image" class="col-form-label">Customer Image</label>
								<input class="form-control" type="file" name="image_" id="image_" accept="image/*" enctype="multipart/form-data">
								{% if form == 'edit' %}
									<input class="form-control image_select" name="image" type="text" id="customer_image" value="" placeholder="Change Customer Image">
									<img src="/static/{{ fv.avatar }}" id="custer_image_preview" />
								{% else %}
									<input class="form-control image_select" name="image" type="text" id="customer_image" value="" placeholder="Select Customer Image">
								{% endif %}
			    			</div>
			    		</div>
			
<!-- section 2 end -->
			        {% endfor %}
<!-- section 3 start -->

			        <div class="col-md-6">
                      		<div class="position-relative form-group">
								<label for="image" class="col-form-label"></label>
	           					
	           					<div>
	                    			<input class="btn btn-success" type="submit" value="{{ 'ADD CUSTOMER' if form == 'add' else 'CONFIRM EDIT' }} " id="add_customer">
	                    			{% if form == 'edit' %}
										<a href="{{ url_for('mods.customers')}}" class="btn btn-warning">CANCEL</a>
									{% endif %}
	                    		</div>
					        </div>
					    </div>
	                </div>
	         
<!-- section 3 end -->

				</form>
				</div>

		</div>

{% endblock %}

app/templates/mods/customer/customers.html
{% extends "home/index.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
		<div id="custmer_list">
        <div class="col-md-12">
        	 <form action="{{ url_for('mods.removeCustomer') }}" method="post" role="form" id="customer_remover">
            <table class="table table-responsive"> 
             
              <!--  class="table table-responsive table-hovered"> -->
              <thead class="thead">
                <tr class="tr well">
                  <td class="th" id="edit_customers" >
                    <a href="{{ url_for('mods.customerAdder') }}"  title="Add a New Customer"><i class="fa fa-plus"></i></a>
                  </td>
                  <td class="th" id="remove_customers" >
                    <i class="fa fa-trash"  title="Remove Selected Customers" data-placement="left"></i>
                  </td>
                  <td class="th">Tax ID</td>
                  <td class="th">Company</td>
                  <td class="th">Name</td>
                  <td class="th">Email</td>
                  <td class="th">Street</td>
                  <td class="th">Street 2</td>
                  <td class="th">City</td>
                  <td class="th">Zip Code</td>
                  <td class="th">Contact</td>
                  <td class="th">Customer Company</td>
                  <td class="th">Type</td>
                  <td class="th">Created</td>
                  <td class="th">Barcode</td>
                  <td class="th">Image</td>
                </tr>
                </thead>
                    
                <tbody class="tbody">
                    {% if customers is iterable and customers|length > 0 %}
                          {% for customer in customers %}

                              <tr class="tr well" id="customer_line">
                                <td class="td"><a href="{{ url_for('mods.editCustomer', customer_id=customer.id ) }}"><i class="fa fa-pen"></i></a></td>
                                <td class="td"><input type="checkbox" name="remove_customer" value="{{ customer.id }}" id="customer_remover"/></td>
                                <td class="td" id="customer_tax" data="{{  customer.tax_id }}">{{  customer.tax_id }}</td>
                                <td class="td" id="company_" data="{{  customer.company.name }}">{{  customer.company.name }}</td>
                                <td class="td" id="customer_name" data="{{  customer.name }}">{{  customer.name }}</td>
                                <td class="td" id="customer_email" data="{{  customer.email }}">{{  customer.email }}</td>
                                <td class="td" id="customer_street" data="{{  customer.street }}">{{  customer.street }}</td>
                                <td class="td" id="customer_street2" data="{{  customer.street2 }}">{{  customer.street2 }}</td>
                                <td class="td" id="customer_city" data="{{  customer.city }}">{{  customer.city }}</td>
                                <td class="td" id="customer_zip" data="{{  customer.zip_code }}">{{  customer.zip_code }}</td>
                                <td class="td" id="customer_contact" data="{{  customer.contact }}">{{  customer.contact }}</td>
                                <td class="td" id="customer_company" data="{{  customer.company_name }}">{{  customer.company_name }}</td>
                                <td class="td" id="customer_type" data="{{  customer.customer_type }}">{{  customer.customer_type }}</td>
                                <td class="td" id="customer_created" data="{{  customer.created_date }}">{{  customer.created_date }}</td>
                                <td class="td" id="customer_barcode" data="{{  customer.barcode }}">{{  customer.barcode }}</td>
                                <td class="td" id="customer_image" data="{{  customer.avatar }}"><img src="static/{{  customer.avatar }}" /></td>
                                
                              </tr>                    

                          {% endfor %}
                        <input type="submit" id="remover_btn"/>
                   
                    {% else %}
                    <span id="no_result_found_message">No Customers Found</span>

                     
                    {% endif %}
                </tbody>
           
            </table>
    		 </form>
      </div>
		</div>	
{% endblock %}